### ISSUE TITLE
README needs updating

### ISSUE THREAD

**Issue by mallorydxw** [peridot-php/peridot-dot-reporter#1]
This does not work:

```
<?php
use Peridot\Reporter\Dot\DotReporterPlugin;

return function(EventEmitterInterface $emitter) {
    $dot = new DotReporterPlugin($emitter);
};
```

It results in this error:

```
% vendor/bin/peridot
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Peridot\Console\Environment::{closure}() must be an instance of EventEmitterInterface, instance of Evenement\EventEmitter given in .../peridot.php:4
Stack trace:
#0 [internal function]: Peridot\Console\Environment->{closure}(Object(Evenement\EventEmitter))
#1 .../vendor/peridot-php/peridot/src/Console/Environment.php(119): call_user_func(Object(Closure), Object(Evenement\EventEmitter))
#2 .../vendor/peridot-php/peridot/src/Console/Environment.php(80): Peridot\Console\Environment->includeConfiguration('/workbench/src/...')
#3 .../vendor/peridot-php/peridot/src/Console/Environment.php(57): Peridot\Console\Environment->loadConfiguration('/workbench/src/...')
```

This works:

```
<?php
return function(\Evenement\EventEmitterInterface $emitter) {
    $dot = new \Peridot\Reporter\Dot\DotReporterPlugin($emitter);
};
```

**Comment by ezzatron** [comment]
Thanks for the report! I'm planning on doing a bunch of repository maintenance soon, so I'll get this fixed up at the same time.

**Comment by dgmstuart** [comment]
@ezzatron any news on this? I was just bitten by the same thing.

**Comment by ezzatron** [comment]
Sorry, we've been working through a few technical issues, trying to get a new release out, and this was kind of low on the priority list. The new example code should work fine.

Note that you could also just drop the `$emitter` type hint, if you're feeling lazy. And there's also the [peridot-jumpstart](https://github.com/peridot-php/peridot-jumpstart) repo for another example of how to set up a [`peridot.php`](https://github.com/peridot-php/peridot-jumpstart/blob/master/peridot.php) config.
